version: '3.9'

services:
  api:
    container_name: 'MUFAI_API'
    image: mufai-web-api
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
      - '3000:3000'
    env_file:
      - '.env'
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: 'MUFAI_API_DB'
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    expose:
      - 5432
    ports:
      - '5432:5432'
    env_file:
      - '.env'
    networks:
      - backend

  pgadmin:
    container_name: pgadmin4-MUFAI
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8090:80'
    networks:
      - backend

networks:
  backend:
    driver: bridge
